# Generated by Django 5.0.6 on 2024-06-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.AddField(
            model_name='car',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_efficiency',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='car',
            name='image_url',
            field=models.CharField(default='car.jpg', max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='max_persons',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='car',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=12.89, max_digits=10),
        ),
        migrations.AddField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(default='car', max_length=50),
        ),
    ]
